---
chdir: /home/deployer/hrlabs.ru/current
environment: production
timeout: 30
log: /home/deployer/hrlabs.ru/current/log/thin.log
pid: /home/deployer/hrlabs.ru/current/tmp/pids/thin.pid
socket: /home/deployer/hrlabs.ru/current/tmp/sockets/thin.sock
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
servers: 2
daemonize: true