---
chdir: /home/deployer/shamatov/current
environment: production
timeout: 30
log: /home/deployer/shared/log/thin.log
pid: /home/deployer/shared/pids/thin.pid
socket: /home/deployer/shared/tmp/thin.sock
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
servers: 2
daemonize: true